export const dataLelang = [
  {
    id: 1,
    namaDebitur: "Sindoro",
    judul: "Rumah Tinggal",
    alamat_singkat: "Pademangan Jakarta Utara",
    alamat:
      "JL. Metro Marina Barat V Blok E No. 37 RT 010 RW 011, Kel. Ancol, Kec. Pademangan, Jakarta Utara.",
    akses_lokasi:
      "Akses menuju lokasi melewati Jalan Puri Marina Raya, akses masuk perumahan persis di samping supermarket Grand Lucky",
    tipe: "Tanah dan Bangunan",
    transaksi: "Jual",
    LT: "84 M2",
    LB: "214 M2",
    KT: "3",
    KM: "2",
    Harga: 2800000000,
    Lantai: "4 Lantai",
    listrik: "-",
    statusAset: "SHGB (Sertifikat Hak Guna Bangunan)",
    furnish: "-",
    material_lantai: "-",
    material_bangunan: "-",
    hadap: "-",
    images: [
      "./sindoro/tampakLuar.jpg",
      "./sindoro/tampakLuar2.jpg",
      "./sindoro/ruangMakanDanKeluarga.jpg",
      "./sindoro/RuangDapur2.jpg",
      "./sindoro/ruangDapur.jpg",
      "./sindoro/kamarTidur.jpg",
      "./sindoro/kamarTidur2.jpg",
    ],
    desImages: [
      "Tampak Luar",
      "Teras Depan/Garasi",
      "Ruang Makan/Keluarga",
      "Dapur",
      "Dapur",
      "Kamar Tidur",
      "Kamar Tidur",
    ],
  },
  {
    id: 2,
    namaDebitur: "Tangguh Dwi Handoyo",
    judul: "Rumah Tinggal",
    alamat_singkat: "Sukmajaya Kota Depok – Provinsi Jawa Barat",
    alamat:
      "JL. Janger I No. 164, RT.05/RW.12 Kelurahan Mekar Jaya, Kecamatan Sukmajaya Kota Depok – Provinsi Jawa Barat",
    akses_lokasi: "-",
    tipe: "Tanah dan Bangunan",
    transaksi: "Jual",
    LT: "89 M2",
    LB: "192 M2",
    KT: "3",
    KM: "2",
    Harga: 1100000000,
    Lantai: "1 Lantai",
    listrik: "-",
    statusAset: "SHM (Sertifikat Hak Milik)",
    furnish: "-",
    material_lantai: "-",
    material_bangunan: "-",
    hadap: "-",
    images: [
      "./tangguhdwih/tampak_depan.jpg",
      "./tangguhdwih/tampak_depan2.jpg",
      "./tangguhdwih/teras_depan.jpg",
      "./tangguhdwih/r_tamu.jpg",
      "./tangguhdwih/kamarTidur2.jpg",
      "./tangguhdwih/atap.jpg",
    ],
    desImages: [
      "Tampak Depan",
      "Tampak Depan",
      "Teras Depan",
      "Ruang Tamu",
      "Kamar Tidur",
      "Atap Rumah",
    ],
  },
  {
    id: 3,
    namaDebitur: "Hari Am Tanjung",
    judul: "Rumah Tinggal",
    alamat_singkat: "Pulogadung, Jakarta Timur",
    alamat:
      "JL. Mustika Jaya No. 6 RT 002 RW 011 Blok S Kav.No.418 & No.434-435, Kel. Rawamangun, Kec.Pulogadung, Jakarta Timur.",
    akses_lokasi:
      "Akses menuju lokasi ± 90 meter dari jalan Balai Pustaka Barat tepat berada di depan KB-TK Aisyiyah 21 Rawamangun di jalan Mustika Jaya",
    tipe: "Tanah dan Bangunan",
    transaksi: "Jual",
    LT: "585 M2",
    LB: "446 M2",
    KT: "5",
    KM: "4",
    Harga: 9400900000,
    Lantai: "2 Lantai",
    listrik: "-",
    statusAset: "SHM (Sertifikat Hak Milik)",
    furnish: "-",
    material_lantai: "-",
    material_bangunan: "-",
    hadap: "-",
    images: [
      "./haritanjung/tampakdepan3.jpg",
      "./haritanjung/ruangtamu.jpg",
      "./haritanjung/ruang_makan.jpeg",
      "./haritanjung/dapur.jpg",
      "./haritanjung/teras.jpeg",
      "./haritanjung/taman.jpeg",
      "./haritanjung/tampakbelakang.jpg",
    ],
    desImages: [
      "Tampak Depan",
      "Ruang Tamu",
      "Ruang Makan",
      "Dapur",
      "Teras Rumah",
      "Taman",
      "Tampak Belakang",
    ],
  },
  //   {
  //     id: 4,
  //     namaDebitur: "Sindoro",
  //     judul: "Rumah Tinggal",
  //     alamat_singkat: "Pademangan Jakarta Utara",
  //     alamat:
  //       "JL. Metro Marina Barat V Blok E No. 37 RT 010 RW 011, Kel. Ancol, Kec. Pademangan, Jakarta Utara.",
  //     akses_lokasi:
  //       "Akses menuju lokasi melewati Jalan Puri Marina Raya, akses masuk perumahan persis di samping supermarket Grand Lucky",
  //     tipe: "Tanah dan Bangunan",
  //     transaksi: "Jual",
  //     LT: "84 M2",
  //     LB: "214 M2",
  //     KT: "",
  //     KM: "",
  //     Harga: "",
  //     Lantai: "4 Lantai",
  //     listrik: "-",
  //     statusAset: "SHGB (Sertifikat Hak Guna Bangunan)",
  //     furnish: "-",
  //     material_lantai: "-",
  //     material_bangunan: "-",
  //     hadap: "-",
  //   },
  //   {
  //     id: 5,
  //     namaDebitur: "Sindoro",
  //     judul: "Rumah Tinggal",
  //     alamat_singkat: "Pademangan Jakarta Utara",
  //     alamat:
  //       "JL. Metro Marina Barat V Blok E No. 37 RT 010 RW 011, Kel. Ancol, Kec. Pademangan, Jakarta Utara.",
  //     akses_lokasi:
  //       "Akses menuju lokasi melewati Jalan Puri Marina Raya, akses masuk perumahan persis di samping supermarket Grand Lucky",
  //     tipe: "Tanah dan Bangunan",
  //     transaksi: "Jual",
  //     LT: "84 M2",
  //     LB: "214 M2",
  //     KT: "",
  //     KM: "",
  //     Harga: "",
  //     Lantai: "4 Lantai",
  //     listrik: "-",
  //     statusAset: "SHGB (Sertifikat Hak Guna Bangunan)",
  //     furnish: "-",
  //     material_lantai: "-",
  //     material_bangunan: "-",
  //     hadap: "-",
  //     images: [],
  //     desImages: [],
  //   },
];
